FROM registry.jetbrains.team/p/prj/containers/projector-idea-u AS build
FROM build AS development

#FROM registry.jetbrains.team/p/prj/containers/projector-idea-u AS development
# RUN apt-get update \
#     && apt-get install -y git
# CMD ["./gradlew", "bootRun"]